---
abstract: 'An SQLite database of derivations of English given names'
author:
  - 'Ron Savage <ron@savage.net.au>'
build_requires:
  Test::More: 0.96
  Test::Pod: 1.44
configure_requires:
  Module::Build: 0.38
dynamic_config: 1
generated_by: 'Module::Build version 0.4002, CPAN::Meta::Converter version 2.120630'
license: artistic
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Lingua-EN-GivenNames
provides:
  Lingua::EN::GivenNames:
    file: lib/Lingua/EN/GivenNames.pm
    version: 1.00
  Lingua::EN::GivenNames::Database:
    file: lib/Lingua/EN/GivenNames/Database.pm
    version: 1.00
  Lingua::EN::GivenNames::Database::Create:
    file: lib/Lingua/EN/GivenNames/Database/Create.pm
    version: 1.00
  Lingua::EN::GivenNames::Database::Download:
    file: lib/Lingua/EN/GivenNames/Database/Download.pm
    version: 1.00
  Lingua::EN::GivenNames::Database::Export:
    file: lib/Lingua/EN/GivenNames/Database/Export.pm
    version: 1.00
  Lingua::EN::GivenNames::Database::Import:
    file: lib/Lingua/EN/GivenNames/Database/Import.pm
    version: 1.00
requires:
  Config::Tiny: 2.14
  DBI: 1.622
  DBIx::Admin::CreateTable: 2.07
  DBIx::Table2Hash: 1.17
  Data::Dumper::Concise: 2.02
  ExtUtils::MakeMaker: 6.62
  File::ShareDir: 1.03
  File::Slurp: 9999.19
  File::Spec: 3.33
  Getopt::Long: 2.38
  HTML::HTML5::Entities: 0.003
  HTML::TreeBuilder: 4.2
  HTTP::Tiny: 0.022
  Hash::FieldHash: 0.12
  IO::File: 1.15
  Lingua::EN::StopWordList: 1
  List::Compare: 0.37
  Pod::Usage: 1.51
  Text::CSV: 1.21
  Text::Xslate: 1.5015
  Unicode::CaseFold: 0.02
  feature: 1.2
  open: 1.08
  parent: 0.225
  strict: 0
  warnings: 0
resources:
  license: http://opensource.org/licenses/artistic-license.php
version: 1.00
